name: grantmckenzie
favicon: null
layout_spectrum: 0.5387360793538392
typography_spectrum: 0.32053310750052333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080c0b'
    - '#f6f6f6'
    - '#57574b'
    - '#bdbdbb'
    - '#bc2632'
  brandStrength: 0.12405822426080704
  lightness: 0.9273015693761408
  saturation: 0.43892709561623633
  rhythmicContrast: 0.6266657346859574
purpose: []
